services:
  postgres:
    image: postgres:16.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "5432:${POSTGRES_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  goapp:
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
    volumes:
      - ./backend/:/app  # ローカルファイルをコンテナ内にマウント
      - /app/tmp

volumes:
  postgres-data:

